### ISSUE TITLE
reflow

### ISSUE THREAD

**Issue by syf1211** [iapYang/vue-video-module#2]
index.js?f302:1 Uncaught TypeError: Cannot read property 'reflow' of undefined
    at eval (index.js?f302:1)    这个错误是怎么回事

**Comment by iapYang** [comment]
报错代码是不是`this.$refs.volume.reflow();`？
@syf1211

**Comment by iapYang** [comment]
希望能提供更报错信息，包括浏览器、OS以及操作过程，方便复现BUG，谢谢。
@syf1211

**Comment by syf1211** [comment]
在控制台就显示这个  Cannot read property 'reflow' of undefined
at eval (index.js?f302:1)   但是他还可以正常执行

**Comment by iapYang** [comment]
@syf1211 version 0.4.6 fixed this bug.
